# Inserts a blank line between shell prompts
add_newline = false

[directory]
style = "blue"

# makes prompt a single line
[line_break]
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✖](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)
format = "took [$duration]($style)"

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_status]
format ='([\[$all_status$ahead_behind\]]($style))'
conflicted = "="
ahead =	"⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count} "
stashed = "↺${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "
style =	"bold red"
disabled = false

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[nodejs]
format = " [$symbol$version]($style) "
symbol = "⬢ "
style = "bold green"
disabled = false
not_capable_style = "bold red"
